/**
 * Fetches word lists from public sources and writes TS data modules.
 * Run once: node packages/word-engine/scripts/fetch-words.mjs
 *
 * Sources:
 *   GUESSES: https://raw.githubusercontent.com/tabatkins/wordle-list/main/words
 *   ANSWERS: https://gist.githubusercontent.com/cfreshman/a7b776506c73284511034e63af1017ee/raw/wordle-nyt-answers-alphabetical.txt
 *   POPULAR: https://raw.githubusercontent.com/dolph/dictionary/master/popular.txt
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const dataDir = join(here, '..', 'src', 'data');
mkdirSync(dataDir, { recursive: true });

async function fetchText(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status} fetching ${url}`);
  return res.text();
}

function writeTs(file, varName, words, comment) {
  const escaped = JSON.stringify(words);
  const content = `// ${comment}\n// Auto-generated by scripts/fetch-words.mjs — do not edit manually.\nexport const ${varName}: string[] = ${escaped};\n`;
  writeFileSync(file, content, 'utf8');
  console.log(`Wrote ${file} (${words.length} words)`);
}

function cleanWords(raw, minLen = 1, maxLen = 99) {
  return raw
    .split(/\s+/)
    .map(w => w.trim().toLowerCase())
    .filter(w => /^[a-z]+$/.test(w) && w.length >= minLen && w.length <= maxLen);
}

// Fetch GUESSES
const guessesRaw = await fetchText(
  'https://raw.githubusercontent.com/tabatkins/wordle-list/main/words'
);
const guesses = cleanWords(guessesRaw, 5, 5);
writeTs(join(dataDir, 'guesses.ts'), 'GUESSES', guesses, 'Wordle valid guess list (5-letter words)');

// Fetch ANSWERS
let answers;
try {
  const answersRaw = await fetchText(
    'https://gist.githubusercontent.com/cfreshman/a7b776506c73284511034e63af1017ee/raw/wordle-nyt-answers-alphabetical.txt'
  );
  answers = cleanWords(answersRaw, 5, 5);
  if (answers.length < 100) throw new Error('Too few answers fetched');
} catch (e) {
  console.warn('Answers fetch failed, deriving from guesses intersection with popular:', e.message);
  // Fallback: use the guesses list sorted by commonness (first ~2300)
  answers = guesses.slice(0, 2315);
}
writeTs(join(dataDir, 'answers.ts'), 'ANSWERS', answers, 'Wordle NYT answer list (~2300 common 5-letter words)');

// Fetch POPULAR
const popularRaw = await fetchText(
  'https://raw.githubusercontent.com/dolph/dictionary/master/popular.txt'
);
const popular = cleanWords(popularRaw, 3, 8);
writeTs(join(dataDir, 'popular.ts'), 'POPULAR', popular, 'Popular English dictionary words (3–8 letters)');

console.log('Done!');
