/**
 * Rebuild ANSWERS as the intersection of the full guess list with the
 * popular-words dictionary — every daily answer must be a common word.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const dataDir = join(here, '..', 'src', 'data');

const extract = (file) =>
  (readFileSync(join(dataDir, file), 'utf8').match(/"([a-z]+)"/g) || []).map((s) => s.slice(1, -1));

const guesses = new Set(extract('guesses.ts'));
const popular5 = extract('popular.ts').filter((w) => w.length === 5);

const answers = popular5.filter((w) => guesses.has(w));
if (answers.length < 1500) {
  throw new Error(`only ${answers.length} common answers — refusing to write a thin list`);
}

const body = `// Daily answer pool: popular dictionary ∩ valid Wordle guesses (${answers.length} common words)
// Sources: github.com/tabatkins/wordle-list + github.com/dolph/dictionary (popular.txt)
// Auto-generated by scripts/fix-answers.mjs — do not edit manually.
export const ANSWERS: string[] = ${JSON.stringify(answers)};
`;
writeFileSync(join(dataDir, 'answers.ts'), body);
console.log('answers rebuilt:', answers.length, 'sample:', answers.slice(0, 8).join(' '));
